refactor: Removed weird if-else statements 🥳
SRM-IST-KTR/githubsrm pull request #160
Opened 2021-12-14 13:13 UTC by Aradhya-Tripathi

# Description

* Improved error handling.
* Removed redundant if-else statements (finally 🥳).

2021-12-14 13:17 UTC, riju561 approved these changes
LGTM

2021-12-14 18:12 UTC, riju561 approved these changes
LGTM

2021-12-17 13:05 UTC, saxenabhishek requested changes
this was so hard to review

2021-12-17 13:11 UTC, Aradhya-Tripathi commented on server/githubsrm/administrator/issue_jwt.py
> +            return
API level exception handling seemed best here as it automatically throws 401 or 403 when authentication fails, thus removing redundant checks. 🤔

2021-12-17 13:12 UTC, Aradhya-Tripathi commented on server/githubsrm/administrator/models.py
> +        return dict(email=[maintainer["email"] for maintainer in maintainers])
But...why? 🤔

2021-12-17 13:12 UTC, Aradhya-Tripathi commented on server/githubsrm/administrator/issue_jwt.py
> +            }
Makes sense lol

2021-12-17 13:13 UTC, Aradhya-Tripathi commented
> this was so hard to review
> 

Had to get rid of weird checks everywhere 🙂

2021-12-17 16:27 UTC, Aradhya-Tripathi commented on server/githubsrm/administrator/issue_jwt.py
> +            }
refactored in 76e1217

2021-12-23 06:42 UTC, saxenabhishek approved these changes

2021-12-23 06:43 UTC, merged